BASE_FS_PATH = ".zeon_git"
BASE_FS_COPY = ".zeon_git_copy"

FS_OBJECTS = f"{BASE_FS_PATH}/objects"
DATABASE_PATH = f"{BASE_FS_PATH}/index"
HOOKS_PATH = f"{BASE_FS_PATH}/hooks"
LIST_FILE_PATH = f"{BASE_FS_PATH}/list.txt"

SNAPSHOT_INTERMEDIATE_DIR = ".zeon_git_snapshot"
SNAPSHOT_DIR_PATH = f"{BASE_FS_PATH}/snapshots"
SNAPSHOT_DIR_IN_INTERMEDIATE_DIR = f"{SNAPSHOT_INTERMEDIATE_DIR}/snapshots"
SNAPSHOTS_DB_PATH = f"{BASE_FS_PATH}/snapshot.txt"
SNAPSHOT_DB_IN_INTERMEDIATE_DIR = f"{SNAPSHOT_INTERMEDIATE_DIR}/snapshot.txt"

INTERMEDIATE_DIR = "zeon_chechkout"
INTERMEDIATE_DATABASE_PATH = f"{INTERMEDIATE_DIR}/index"
INTERMEDIATE_OBJECTS = f"{INTERMEDIATE_DIR}/objects"

CHECKOUT_DIRS = "checkout"
