BASE_FS_PATH = ".zeon_git"
BASE_FS_COPY = ".zeon_git_copy"
DATABASE_NAME = "index"
LIST_FILE_NAME = "list.txt"

FS_OBJECTS = f"{BASE_FS_PATH}/objects"
DATABASE_PATH = f"{BASE_FS_PATH}/{DATABASE_NAME}"
HOOKS_PATH = f"{BASE_FS_PATH}/hooks"
LIST_FILE_PATH = f"{BASE_FS_PATH}/{LIST_FILE_NAME}"

SNAPSHOT_INTERMEDIATE_DIR = ".zeon_git_snapshot"
SNAPSHOT_DIR_PATH = f"{BASE_FS_PATH}/snapshots"
SNAPSHOT_DIR_IN_INTERMEDIATE_DIR = f"{SNAPSHOT_INTERMEDIATE_DIR}/snapshots"
SNAPSHOTS_DB_PATH = f"{BASE_FS_PATH}/snapshot.txt"
SNAPSHOT_DB_IN_INTERMEDIATE_DIR = f"{SNAPSHOT_INTERMEDIATE_DIR}/snapshot.txt"

INTERMEDIATE_DIR = "intermediate_dir"
INTERMEDIATE_DATABASE_PATH = f"{INTERMEDIATE_DIR}/{DATABASE_NAME}"
INTERMEDIATE_OBJECTS = f"{INTERMEDIATE_DIR}/objects"
INTERMEDIATE_DATABASE = f"{INTERMEDIATE_DIR}/{DATABASE_NAME}"
INTERMEDIATE_LIST_FILE = f"{INTERMEDIATE_DIR}/{LIST_FILE_NAME}"

CHECKOUT_DIRS = "checkout"

COMMIT_DIR = f"{INTERMEDIATE_DIR}/commit"
